# ============================================================
# KdV solver parameters
# ============================================================

N: 512
systemsize: 31.41592653589793   # 10π
nonlinparameter: 1.0
dt: 1.0e-5
total_time: 2.0
